// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package config

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson8ceb9162DecodeGithubComXantiniumMetrixInternalConfig(in *jlexer.Lexer, out *serverConfig) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "address":
			if in.IsNull() {
				in.Skip()
				out.Addr = nil
			} else {
				if out.Addr == nil {
					out.Addr = new(string)
				}
				*out.Addr = string(in.String())
			}
		case "store_file":
			if in.IsNull() {
				in.Skip()
				out.StoragePath = nil
			} else {
				if out.StoragePath == nil {
					out.StoragePath = new(string)
				}
				*out.StoragePath = string(in.String())
			}
		case "key":
			if in.IsNull() {
				in.Skip()
				out.PrivateKey = nil
			} else {
				if out.PrivateKey == nil {
					out.PrivateKey = new(string)
				}
				*out.PrivateKey = string(in.String())
			}
		case "crypto_key":
			if in.IsNull() {
				in.Skip()
				out.CryptoPrivateKey = nil
			} else {
				if out.CryptoPrivateKey == nil {
					out.CryptoPrivateKey = new(string)
				}
				*out.CryptoPrivateKey = string(in.String())
			}
		case "database_dsn":
			if in.IsNull() {
				in.Skip()
				out.DatabaseConnStr = nil
			} else {
				if out.DatabaseConnStr == nil {
					out.DatabaseConnStr = new(string)
				}
				*out.DatabaseConnStr = string(in.String())
			}
		case "store_interval":
			if in.IsNull() {
				in.Skip()
				out.StoreInterval = nil
			} else {
				if out.StoreInterval == nil {
					out.StoreInterval = new(string)
				}
				*out.StoreInterval = string(in.String())
			}
		case "is_dev":
			if in.IsNull() {
				in.Skip()
				out.IsDev = nil
			} else {
				if out.IsDev == nil {
					out.IsDev = new(bool)
				}
				*out.IsDev = bool(in.Bool())
			}
		case "is_profiling":
			if in.IsNull() {
				in.Skip()
				out.IsProfilingEnabled = nil
			} else {
				if out.IsProfilingEnabled == nil {
					out.IsProfilingEnabled = new(bool)
				}
				*out.IsProfilingEnabled = bool(in.Bool())
			}
		case "restore":
			if in.IsNull() {
				in.Skip()
				out.RestoreStorage = nil
			} else {
				if out.RestoreStorage == nil {
					out.RestoreStorage = new(bool)
				}
				*out.RestoreStorage = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8ceb9162EncodeGithubComXantiniumMetrixInternalConfig(out *jwriter.Writer, in serverConfig) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix[1:])
		if in.Addr == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Addr))
		}
	}
	{
		const prefix string = ",\"store_file\":"
		out.RawString(prefix)
		if in.StoragePath == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.StoragePath))
		}
	}
	{
		const prefix string = ",\"key\":"
		out.RawString(prefix)
		if in.PrivateKey == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.PrivateKey))
		}
	}
	{
		const prefix string = ",\"crypto_key\":"
		out.RawString(prefix)
		if in.CryptoPrivateKey == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.CryptoPrivateKey))
		}
	}
	{
		const prefix string = ",\"database_dsn\":"
		out.RawString(prefix)
		if in.DatabaseConnStr == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.DatabaseConnStr))
		}
	}
	{
		const prefix string = ",\"store_interval\":"
		out.RawString(prefix)
		if in.StoreInterval == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.StoreInterval))
		}
	}
	{
		const prefix string = ",\"is_dev\":"
		out.RawString(prefix)
		if in.IsDev == nil {
			out.RawString("null")
		} else {
			out.Bool(bool(*in.IsDev))
		}
	}
	{
		const prefix string = ",\"is_profiling\":"
		out.RawString(prefix)
		if in.IsProfilingEnabled == nil {
			out.RawString("null")
		} else {
			out.Bool(bool(*in.IsProfilingEnabled))
		}
	}
	{
		const prefix string = ",\"restore\":"
		out.RawString(prefix)
		if in.RestoreStorage == nil {
			out.RawString("null")
		} else {
			out.Bool(bool(*in.RestoreStorage))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v serverConfig) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8ceb9162EncodeGithubComXantiniumMetrixInternalConfig(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v serverConfig) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8ceb9162EncodeGithubComXantiniumMetrixInternalConfig(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *serverConfig) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8ceb9162DecodeGithubComXantiniumMetrixInternalConfig(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *serverConfig) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8ceb9162DecodeGithubComXantiniumMetrixInternalConfig(l, v)
}
func easyjson8ceb9162DecodeGithubComXantiniumMetrixInternalConfig1(in *jlexer.Lexer, out *agentConfig) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "address":
			if in.IsNull() {
				in.Skip()
				out.Addr = nil
			} else {
				if out.Addr == nil {
					out.Addr = new(string)
				}
				*out.Addr = string(in.String())
			}
		case "key":
			if in.IsNull() {
				in.Skip()
				out.PrivateKey = nil
			} else {
				if out.PrivateKey == nil {
					out.PrivateKey = new(string)
				}
				*out.PrivateKey = string(in.String())
			}
		case "crypto_key":
			if in.IsNull() {
				in.Skip()
				out.CryptoPublicKey = nil
			} else {
				if out.CryptoPublicKey == nil {
					out.CryptoPublicKey = new(string)
				}
				*out.CryptoPublicKey = string(in.String())
			}
		case "poll_interval":
			if in.IsNull() {
				in.Skip()
				out.PollInterval = nil
			} else {
				if out.PollInterval == nil {
					out.PollInterval = new(string)
				}
				*out.PollInterval = string(in.String())
			}
		case "report_interval":
			if in.IsNull() {
				in.Skip()
				out.ReportInterval = nil
			} else {
				if out.ReportInterval == nil {
					out.ReportInterval = new(string)
				}
				*out.ReportInterval = string(in.String())
			}
		case "report_rate_limit":
			if in.IsNull() {
				in.Skip()
				out.ReportRateLimit = nil
			} else {
				if out.ReportRateLimit == nil {
					out.ReportRateLimit = new(int)
				}
				*out.ReportRateLimit = int(in.Int())
			}
		case "is_dev":
			if in.IsNull() {
				in.Skip()
				out.IsDev = nil
			} else {
				if out.IsDev == nil {
					out.IsDev = new(bool)
				}
				*out.IsDev = bool(in.Bool())
			}
		case "is_profiling":
			if in.IsNull() {
				in.Skip()
				out.IsProfilingEnabled = nil
			} else {
				if out.IsProfilingEnabled == nil {
					out.IsProfilingEnabled = new(bool)
				}
				*out.IsProfilingEnabled = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8ceb9162EncodeGithubComXantiniumMetrixInternalConfig1(out *jwriter.Writer, in agentConfig) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix[1:])
		if in.Addr == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Addr))
		}
	}
	{
		const prefix string = ",\"key\":"
		out.RawString(prefix)
		if in.PrivateKey == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.PrivateKey))
		}
	}
	{
		const prefix string = ",\"crypto_key\":"
		out.RawString(prefix)
		if in.CryptoPublicKey == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.CryptoPublicKey))
		}
	}
	{
		const prefix string = ",\"poll_interval\":"
		out.RawString(prefix)
		if in.PollInterval == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.PollInterval))
		}
	}
	{
		const prefix string = ",\"report_interval\":"
		out.RawString(prefix)
		if in.ReportInterval == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.ReportInterval))
		}
	}
	{
		const prefix string = ",\"report_rate_limit\":"
		out.RawString(prefix)
		if in.ReportRateLimit == nil {
			out.RawString("null")
		} else {
			out.Int(int(*in.ReportRateLimit))
		}
	}
	{
		const prefix string = ",\"is_dev\":"
		out.RawString(prefix)
		if in.IsDev == nil {
			out.RawString("null")
		} else {
			out.Bool(bool(*in.IsDev))
		}
	}
	{
		const prefix string = ",\"is_profiling\":"
		out.RawString(prefix)
		if in.IsProfilingEnabled == nil {
			out.RawString("null")
		} else {
			out.Bool(bool(*in.IsProfilingEnabled))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v agentConfig) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8ceb9162EncodeGithubComXantiniumMetrixInternalConfig1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v agentConfig) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8ceb9162EncodeGithubComXantiniumMetrixInternalConfig1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *agentConfig) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8ceb9162DecodeGithubComXantiniumMetrixInternalConfig1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *agentConfig) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8ceb9162DecodeGithubComXantiniumMetrixInternalConfig1(l, v)
}
